### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by jasonfb** [ariatemplates/git-release-notes#12]
After using git-release-notes successfully for several months, this morning I am unable to get it to work. Whenever I run the command, I get no output. Either on the command line or when attempted to output to a disk, the command returns a completely empty result.

AFAIK, I made no changes to my system so this is a complete surprise.

Please advise.

**Comment by jakub-g** [comment]
Hi, what is your OS and what does this print?

```
npm --version
node --version
```

Any details to reproduce your issue?

**Comment by jasonfb** [comment]
```
jason@Jasons-MB-Air-2:mack_weldon (master)$ npm --version
2.3.0
jason@Jasons-MB-Air-2:mack_weldon (master)$ node --version
v0.10.35
```

I haven't tried it on a test repository -- this just started happening this morning (obviously, when I was preparing the release notes for our morning deploy!)

I will create an new git repo, make some tests commits, and see if it still does it there.

**Comment by piuccio** [comment]
any chance you could try a newer version of node? 0.10 has reached its [end of life](https://github.com/nodejs/LTS)

**Comment by jasonfb** [comment]
Sure, done:
jason@Jasons-MB-Air-2:mack_weldon (master)$ npm -v
3.10.9
jason@Jasons-MB-Air-2:mack_weldon (master)$ node -v
v7.2.0


Unfortunately, the same symptom persists. I have some meetings this morning but will get back to this later today.

**Comment by jasonfb** [comment]
this was some PEBKAC. sorry. I had accidentally messed up my ejs file.
