### ISSUE TITLE
How to filter commits without startwith feat or fix type?

### ISSUE THREAD

**Issue by XGiton** [ariatemplates/git-release-notes#13]
Hi, There are four type commits in my project, and I want output commits which type is "feat" or "fix". How should the command be?

My commit follow below format:

```
feat(scope): subject

  - change1
  - change2
```

**Comment by piuccio** [comment]
Do you mean you want to filter only two of the four types and ignore commits that are not `feat` or `fix`?

**Comment by XGiton** [comment]
@piuccio
Yes.

**Comment by piuccio** [comment]
Oh sorry, I should've inferred from the title :facepalm:

It's not possible at the time but it's not too difficult to implement. When processing [the title](https://github.com/ariatemplates/git-release-notes/blob/master/lib/git.js#L86) we need a way to filter out unknown types

Fancy writing a PR?

**Comment by piuccio** [comment]
This could be fixed by #7

**Comment by XGiton** [comment]
Thanks!
This sounds interesting, but I have too much on my plate at the moment.(*^__^*)
