### ISSUE TITLE
bootstrap template

### ISSUE THREAD

**Issue by neutmute** [ariatemplates/git-release-notes#20]
Thanks for this tool. I updated the base template for my own use to use [bootstrap](http://getbootstrap.com/) and [datatables](https://datatables.net/) and it looks a lot nicer.

Would you like a PR to add this sample? 
It uses CDN sources for script/css and so is still a self contained one pager.

The PR would contain a single new file: `/templates/html-bootstrap.ejs`

**Comment by piuccio** [comment]
sounds good to me
