### ISSUE TITLE
Make date formatting library available

### ISSUE THREAD

**Issue by neutmute** [ariatemplates/git-release-notes#22]
Hey - I propose adding a date formatting library available as a local variable in the template
That would save a bit of code in the `html-bootstrap` template and be more flexible for consumers.

I'm not a react expert, I propose perhaps https://github.com/date-fns/date-fns ?
Looks like the most active currently.

There is also https://www.npmjs.com/package/dateformat

Open to suggestions - anything is better than the half baked code I added to the bootstrap template ;)

btw: I'm happy to do the PR for this

**Comment by neutmute** [comment]
Any thoughts on this @piuccio?

**Comment by piuccio** [comment]
didn't really give much thought to this, but anything that doesn't require JS on the output page would be best

**Comment by neutmute** [comment]
cool - no preference as to date library? I'll try `date-fns` if you no strong preference
