### ISSUE TITLE
Template Config

### ISSUE THREAD

**Issue by neutmute** [ariatemplates/git-release-notes#25]
This project is working very well for me and looks great. One more requirement though is that in my company we have multiple repositories and I'd like to be able to have a *single, reusable template* for all repositories but with very small customisations per repository.

For example, in my custom template I have added links for each commit to the BitBucket project where our code is hosted. The URL is different per project eg:

* http://bitbucket/acme-corp/project-apple/commit/-hash-
* http://bitbucket/acme-corp/project-banana/commit/-hash-
* http://bitbucket/acme-corp/project-carrot/commit/-hash-

To support this custom URL per repo, I would like to be able to pass parameters from the command line to the template directly - without `git-release-notes` needing to know about / parse them

I propose a third optional CLI parameter that would be a path to a JSON file that would be loaded from the file system, hydrated to a JSON object and then passed into the template as a variable named `templateConfig`. Interpretation is then strictly up to the template.

In my case I would pass in something like

```
{
  "repoName": "Project Apple",
  "gitRepoUrl": "http://bitbucket/acme-corp/project-apple"
}
```

but the structure could be anything that the template author requires.

Thoughts?

**Comment by piuccio** [comment]
good idea, but rather then a third optional parameter I prefer a named parameter. That way it's clear what's mandatory (revision and template) and what's optional

`git-release-notes --templateConfig some.json ...`

Maybe `templateData` is a better name, `config` makes me think of values that change the way templating works, in this case we're simply passing extra values to the template

**Comment by neutmute** [comment]
sounds good - will implement as you suggest

**Comment by piuccio** [comment]
Version `1.1.0` allows external scripts to modify the commits list and inject any custom data in the template. Is there something else that needs to be done here?

**Comment by neutmute** [comment]
works great - thanks
