### ISSUE TITLE
external script location

### ISSUE THREAD

**Issue by neutmute** [ariatemplates/git-release-notes#30]
One problem I ran into in v1.1 was the external script path is relative to the current working directory.

I expected that to be an absolute path - the same as the ejs template

Was that by design?

Apart from that - it is working well and I could make my external script all typescript which is awesome.

**Comment by piuccio** [comment]
it's a relative path simply because I didn't notice the template was absolute 😓  Agree that should be the same as template

**Comment by piuccio** [comment]
This is now fixed in version `2.0.0`, thanks

**Comment by piuccio** [comment]
They're both supposed to be absolute, but maybe the template path works either way

**Comment by piuccio** [comment]
@sa-emcvey sorry to dig up an old issue, but as of version `3.0.0` all paths should work, relative or absolute is irrelevant
