### ISSUE TITLE
Output bootstrap html without Html, Head and Body tags

### ISSUE THREAD

**Issue by ct14it** [ariatemplates/git-release-notes#34]
Hi there, 

is it possible to output a Bootstrap HTML  template so that that you only get the `<div class="container" role="main">` div contents and nothing else?

I'd like to embed the output into a separate page (which I load as a Html.Partial)

Cheers!
-Chris

**Comment by piuccio** [comment]
Hi Chris

There's a way, yes. Copy the bootstrap template from [here](https://github.com/ariatemplates/git-release-notes/blob/master/templates/html-bootstrap.ejs), remove what you don't need and save the file somewhere in your repo.

You can then run `git-release-notes v1..v2 /path/to/template.ejs`

I don't feel like adding multiple variations of the same template in this repo, so you'll have to use a custom template

**Comment by ct14it** [comment]
Nice one thank you very much!
