### ISSUE TITLE
Expose a node API

### ISSUE THREAD

**Issue by adierkens** [ariatemplates/git-release-notes#35]
Would you be open to exposing a node API for generating the release notes?

It'd be nice to be able to build tools on top of this project, without having to use subprocesses.

**Comment by piuccio** [comment]
oh yeah that would be amazing. Let me find some time to implement this.

You can always go ahead and send a PR

**Comment by adierkens** [comment]
Awesome! I can put something together.

**Comment by piuccio** [comment]
Hey, I finally had some time to work on this issue.

You can use the module API starting from version `3.0.0`, refer to the README or the [changelog](https://github.com/ariatemplates/git-release-notes/releases/tag/v3.0.0)
