### ISSUE TITLE
html generated this wrong

### ISSUE THREAD

**Issue by Erick-Zanetti** [ariatemplates/git-release-notes#37]
when I generate the command to create the html, it looks strange and renders with ├º├ those special characters.

**Comment by piuccio** [comment]
can you paste here the command you're using? Any additional information, like operating system, default language, or possibly a repo where I can reproduce?

**Comment by Erick-Zanetti** [comment]
The command I am using is git-release-notes origin html > changelog.html, and the default language is Brazilian Portuguese in the file changelog.html that is being generated all characters of my language are left with that strange symbol.

**Comment by Erick-Zanetti** [comment]
![image](https://user-images.githubusercontent.com/29898441/30325240-5c592ffa-979a-11e7-9ae8-93db1ee5340f.png)
Exemplo de como fica

**Comment by piuccio** [comment]
@Erick-Zanetti did you solve it somehow?
