### ISSUE TITLE
How can I get the tags

### ISSUE THREAD

**Issue by stephanebouget** [ariatemplates/git-release-notes#48]
How can I get the tags into the callback ?
I want to retrieve all commits from 0.0.0 tag to HEAD,
and I want to get tag with commit id when exists.

I tried to use
`const OPTIONS = {
	branch: 'master',
	o: ['tags']
};`
`const RANGE = '0.0.0...';
`

but it return the same result without tags.

tks !

**Comment by piuccio** [comment]
It's not possible right now, but you can try sending a PR.

What you need to do is [change this line](https://github.com/ariatemplates/git-release-notes/blob/master/lib/git.js#L55) and add a parameter `tag:%D` right after `title`.

it'll include the following text `tag: v1.20.0` inside `tag`.

`%D` is the ref name, so it could be `heads, tags, remotes` so you might have to filter only tags and remove `tag: ` when parsing the line

**Comment by piuccio** [comment]
I've merged your PR with some changes and released as version `4.0.0`, hope it works for you
