### ISSUE TITLE
add CI 

### ISSUE THREAD

**Issue by mapleeit** [ariatemplates/git-release-notes#55]
I noticed that there is a travis config file in the project, but it seems never work. I'm willing to help fixing it.

**Comment by piuccio** [comment]
My bad, the configuration on travis allowed builds on branch push, but not on pull requests.
I've changed that, it should work now. Let's see if it run when you update your PR and then close this if everything is ok

**Comment by mapleeit** [comment]
#54  It indeed works now. So close this.
