### ISSUE TITLE
TS types support 

### ISSUE THREAD

**Issue by mapleeit** [ariatemplates/git-release-notes#56]
Noticed that there is no types definition either in the package nor on the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

It would be a nice experience if we provide types define files. I could help to do that.

**Comment by piuccio** [comment]
I'm not very keen on defining types inside the files. I don't want to use compilers/transpilers/whatevers.
If there's a way to generate types while at the same time guarantee that the module can be used simply with node 8, I'm happy

**Comment by mapleeit** [comment]
Defining types doesn't mean using TS compilers. ; )

There are two ways to achieve this:

1. Add a typing file like `index.d.ts` to the root directory without any other change. People could enjoy the convenience of types out of box. E.g. [axios](https://github.com/axios/axios)

2. Post it on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). This way doesn't change anything within this package. It will create a new npm package named `@types/git-release-notes`. People must install it before use TS types.

I prefer the first one, but could do with the other.

**Comment by piuccio** [comment]
I like the first one too!

**Comment by mapleeit** [comment]
Close.
